# Generated by Django 4.2.5 on 2023-09-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
