# Generated by Django 4.2.5 on 2023-09-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_cartitem_options_cart_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoorterButtons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo', models.TextField()),
                ('phone_number', models.CharField(max_length=255)),
                ('mail', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Кнопка в футере',
                'verbose_name_plural': 'Кнопки в футере',
            },
        ),
    ]
