# Generated by Django 4.2.5 on 2023-09-12 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_foorterbuttons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoorterButtons',
        ),
    ]
